# Generated by Django 5.1.1 on 2024-09-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('quantidade_aulas', models.IntegerField()),
                ('data_aulas', models.DateField()),
                ('professor', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
    ]
