# Generated by Django 5.1.1 on 2025-02-26 19:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0003_aula_dias_antes_aula_mensagem_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_disparo', models.DateField()),
                ('contato', models.JSONField(blank=True, null=True)),
                ('intervalo_disparo', models.IntegerField(help_text='Intervalo de disparo de mensagens')),
                ('mensagem_notificacao', models.TextField(blank=True, help_text='Mensagem personalizada para a notificação.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
    ]
