# Generated by Django 5.1.1 on 2025-02-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0004_mensagem_delete_aula'),
    ]

    operations = [
    ]
