# Generated by Django 5.1.1 on 2025-02-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0005_auto_20250226_1610'),
    ]

    operations = [
    ]
