# Generated by Django 5.1.1 on 2025-02-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0006_remove_mensagem_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='data_disparo',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='dias_disparo',
            field=models.JSONField(default=[], help_text='Dias da semana para disparo (0=Segunda, 1=Terça, ..., 6=Domingo)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagem',
            name='horario_disparo',
            field=models.TimeField(default='14:30:00', help_text='Horário para disparo de mensagens'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='contato',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
