# Generated by Django 5.1.1 on 2025-03-14 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('formulario_professores', '0009_enviadas'),
    ]

    
