# Generated by Django 5.1.1 on 2025-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0011_usermessagelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessagelimit',
            name='limite_diario',
            field=models.IntegerField(default=65),
        ),
    ]
