# Generated by Django 5.1.1 on 2025-03-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0012_alter_usermessagelimit_limite_diario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessagelimit',
            options={'verbose_name': 'Limite de Mensagens do Usuário', 'verbose_name_plural': 'Limites de Mensagens dos Usuários'},
        ),
        migrations.AddField(
            model_name='mensagem',
            name='modo_envio',
            field=models.CharField(choices=[('texto', 'Somente Texto'), ('midia', 'Somente Mídia'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='ordem_envio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tipo_envio',
            field=models.CharField(choices=[('texto_primeiro', 'Texto Primeiro'), ('midia_primeiro', 'Mídia Primeiro')], default='texto_primeiro', max_length=15),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='dias_disparo',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='horario_disparo',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='intervalo_disparo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem_notificacao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MidiaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('documento', 'Documento')], max_length=10)),
                ('ordem_envio', models.IntegerField(default=0)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='formulario_professores.mensagem')),
            ],
        ),
    ]
