# Generated by Django 5.1.1 on 2025-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0013_alter_usermessagelimit_options_mensagem_modo_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('documento', 'Documento')], max_length=10)),
                ('link', models.URLField(max_length=500)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
