# Generated by Django 5.1.1 on 2025-03-19 18:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0014_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(default='', storage=storages.backends.s3.S3Storage(), upload_to='midia/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='midia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
