# Generated by Django 5.1.1 on 2025-03-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0015_midia_arquivo_alter_midia_descricao_alter_midia_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='midias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
