# Generated by Django 5.1.1 on 2025-03-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0016_midia_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midia',
            old_name='user',
            new_name='usuario',
        ),
    ]
