# Generated by Django 5.1.1 on 2025-03-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0017_rename_user_midia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
