# Generated by Django 5.1.1 on 2025-03-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0018_alter_midia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midiamensagem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='midiamensagem',
            name='ordem_envio',
        ),
        migrations.RemoveField(
            model_name='midiamensagem',
            name='tipo',
        ),
        migrations.AddField(
            model_name='midiamensagem',
            name='midia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='midia_mensagens', to='formulario_professores.midia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='midiamensagem',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_midias', to='formulario_professores.mensagem'),
        ),
    ]
