# Generated by Django 5.1.1 on 2025-05-28 00:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0019_remove_midiamensagem_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='id_campanha',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Loteamento'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='modo_envio',
            field=models.CharField(choices=[('texto', 'Somente Texto'), ('midia', 'Somente Mídia'), ('ambos', 'Ambos')], default='texto', max_length=10),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
