# Generated by Django 5.1.1 on 2025-08-09 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0020_mensagem_id_campanha_alter_mensagem_modo_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancia',
            name='id_instancia',
        ),
        migrations.RemoveField(
            model_name='instancia',
            name='token_instancia',
        ),
        migrations.AddField(
            model_name='instancia',
            name='conectado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instancia',
            name='dados_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='nome_instancia',
            field=models.CharField(default='instancia_padrao', help_text='Nome único para a instância/sessão. Ex: instancia_padrao', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancia',
            name='ultimo_status_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='formulario_professores.midia'),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento')], max_length=10),
        ),
        migrations.CreateModel(
            name='EvolutionAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_host', models.URLField(help_text='URL base da sua instância Evolution API. Ex: http://localhost:8080', max_length=255)),
                ('api_key', models.CharField(help_text='API Key gerada pela sua instância Evolution API.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração da Evolution API',
                'verbose_name_plural': 'Configurações da Evolution API',
            },
        ),
    ]
