# Generated by Django 5.1.1 on 2025-08-09 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0021_remove_instancia_id_instancia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionapisettings',
            name='api_host',
            field=models.CharField(help_text='URL base da sua instância Evolution API. Ex: http://evolution_api:8080', max_length=255, verbose_name='URL da API Evolution'),
        ),
        migrations.AlterField(
            model_name='evolutionapisettings',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='Chave da API (API Key)'),
        ),
        migrations.AlterField(
            model_name='evolutionapisettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='evolutionapisettings',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
