# Generated by Django 5.1.1 on 2025-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_professores', '0022_alter_evolutionapisettings_api_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
